name       : libmspub
version    : 0.1.2
release    : 3
source     :
    - http://dev-www.libreoffice.org/src/libmspub/libmspub-0.1.2.tar.xz : b0baabf82d20c08ad000e80fa02154ce2f2ffde1ee60240d6e3a917c3b35560f
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting MS Publisher files
description: |
    libmspub is a library and a set of tools for reading and converting MS Publisher files.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
