name       : libmspub
version    : 0.1.3
release    : 4
source     :
    - https://dev-www.libreoffice.org/src/libmspub/libmspub-0.1.3.tar.xz : f0225f0ff03f6bec4847d7c2d8719a36cafc4b97a09e504b610372cc5b981c97
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting MS Publisher files
description: |
    libmspub is a library and a set of tools for reading and converting MS Publisher files.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
