name       : libmspub
version    : 0.1.4
release    : 7
source     :
    - https://dev-www.libreoffice.org/src/libmspub/libmspub-0.1.4.tar.xz : ef36c1a1aabb2ba3b0bedaaafe717bf4480be2ba8de6f3894be5fd3702b013ba
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting MS Publisher files
description: |
    libmspub is a library and a set of tools for reading and converting MS Publisher files.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
